-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public."Departments"
(
    dept_no "char",
    dept_name "char",
    PRIMARY KEY (dept_no)
);

CREATE TABLE public.dept_emp
(
    emp_no "char",
    dept_no "char"
);

CREATE TABLE public.dept_manager
(
    emp_no "char",
    dept_no "char"
);

CREATE TABLE public.employees
(
    emp_no "char",
    emp_title_id "char",
    birth_date "char",
    first_name "char",
    last_name "char",
    sex "char",
    hire_date "char"
);

CREATE TABLE public.salaries
(
    emp_no "char",
    salary "char"
);

CREATE TABLE public.titles
(
    title_id "char",
    title "char"
);

ALTER TABLE public."Departments"
    ADD FOREIGN KEY (dept_no)
    REFERENCES public.dept_emp (dept_no)
    NOT VALID;


ALTER TABLE public.employees
    ADD FOREIGN KEY (emp_title_id)
    REFERENCES public.titles (title_id)
    NOT VALID;


ALTER TABLE public.employees
    ADD FOREIGN KEY (emp_no)
    REFERENCES public.salaries (emp_no)
    NOT VALID;


ALTER TABLE public.dept_manager
    ADD FOREIGN KEY (dept_no)
    REFERENCES public."Departments" (dept_no)
    NOT VALID;


ALTER TABLE public.dept_manager
    ADD FOREIGN KEY (emp_no)
    REFERENCES public.employees (emp_no)
    NOT VALID;


ALTER TABLE public.dept_emp
    ADD FOREIGN KEY (emp_no)
    REFERENCES public.employees (emp_no)
    NOT VALID;

END;